//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipHistory
    {
        public int ShipperID { get; set; }
        public int OrderID { get; set; }
        public Nullable<decimal> RecievedMoney { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
